/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://www.caspian-routes.com',
  generateRobotsTxt: true,
  defaultChangefreq: 'weekly',
  defaultPriority: 0.7,
  exclude: [
    '/admin',
    '/admin/*',
    '/partner-portal',
    '/partner-portal/*',
    '/partner-dashboard',
    '/partner-dashboard/*',
    '/partner-quote',
    '/partner-quote/*',
    '/dashboard',
    '/dashboard/*',
    '/profile',
    '/auth',
    '/auth/*',
    '/book',
    '/book/*',
    '/bookings',
    '/bookings/*',
    '/saved',
    '/provider',
    '/provider/*',
  ],
}